# Generated by Django 4.1.7 on 2023-03-26 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truckdriverapi', '0003_alter_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='truckdriverapi.city'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='truckdriverapi.language'),
        ),
    ]
