# Generated by Django 4.1.7 on 2023-03-26 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truckdriverapi', '0004_alter_driver_city_alter_driver_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Cities'},
        ),
        migrations.AddField(
            model_name='driver',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='driver',
            name='assigned_truck',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='truckdriverapi.assignedtruck'),
        ),
    ]
