# Generated by Django 4.1.7 on 2023-03-26 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('truckdriverapi', '0005_alter_city_options_driver_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='id',
        ),
        migrations.AlterField(
            model_name='driver',
            name='assigned_truck',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='truckdriverapi.assignedtruck'),
        ),
    ]
