# Generated by Django 4.1.7 on 2023-04-01 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('truckdriverapi', '0006_remove_driver_id_alter_driver_assigned_truck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='assigned_truck',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='city',
        ),
        migrations.RemoveField(
            model_name='driver',
            name='language',
        ),
        migrations.DeleteModel(
            name='AssignedTruck',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
